
server:
  port: 8889

spring:
  application:
    name: sun-shop-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study
    username: study
    password: mystudy00!

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

system:
  upload-path: D:\\test\\files\\